-- MySQL Script generated by MySQL Workbench
-- Thu Nov  8 08:25:05 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BoreholeMonitorDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BoreholeMonitorDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BoreholeMonitorDB` DEFAULT CHARACTER SET utf8 ;
USE `BoreholeMonitorDB` ;

-- -----------------------------------------------------
-- Table `BoreholeMonitorDB`.`Borehole_Type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BoreholeMonitorDB`.`Borehole_Type` (
  `TYPE_ID` INT NOT NULL AUTO_INCREMENT,
  `TYPE_DESCRIPTION` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`TYPE_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BoreholeMonitorDB`.`Location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BoreholeMonitorDB`.`Location` (
  `LOCATION_NUM` INT NOT NULL AUTO_INCREMENT,
  `LATITUDE` FLOAT NOT NULL,
  `LONGITUDE` FLOAT NOT NULL,
  `ELEVATION` INT NOT NULL,
  PRIMARY KEY (`LOCATION_NUM`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BoreholeMonitorDB`.`Borehole`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BoreholeMonitorDB`.`Borehole` (
  `BOREHOLE_ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(200) NOT NULL,
  `TYPE_ID` INT NOT NULL,
  `LOCATION_NUM` INT NOT NULL,
  PRIMARY KEY (`BOREHOLE_ID`),
  INDEX `fk_Borehole_Borehole_Type1_idx` (`TYPE_ID` ASC) VISIBLE,
  INDEX `fk_Borehole_Location1_idx` (`LOCATION_NUM` ASC) VISIBLE,
  CONSTRAINT `fk_Borehole_Borehole_Type1`
    FOREIGN KEY (`TYPE_ID`)
    REFERENCES `BoreholeMonitorDB`.`Borehole_Type` (`TYPE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Borehole_Location1`
    FOREIGN KEY (`LOCATION_NUM`)
    REFERENCES `BoreholeMonitorDB`.`Location` (`LOCATION_NUM`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BoreholeMonitorDB`.`Water_Level_Recording`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BoreholeMonitorDB`.`Water_Level_Recording` (
  `WATER_LEVEL_ID` INT NOT NULL AUTO_INCREMENT,
  `CAPTURE_DATE` DATE NOT NULL,
  `LEVEL_READING` INT NOT NULL,
  `BOREHOLE_ID` INT NOT NULL,
  PRIMARY KEY (`WATER_LEVEL_ID`),
  INDEX `fk_Water_Level_Borehole1_idx` (`BOREHOLE_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Water_Level_Borehole1`
    FOREIGN KEY (`BOREHOLE_ID`)
    REFERENCES `BoreholeMonitorDB`.`Borehole` (`BOREHOLE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
